# Generated by Django 4.0.5 on 2022-07-26 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_user_year_of_admission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Video_description', models.CharField(max_length=300)),
                ('Video_Link', models.URLField(max_length=400)),
                ('Date_Time', models.DateField()),
                ('Video_status', models.CharField(choices=[('1', 'Private'), ('2', 'Public')], max_length=100)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user_id')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user_id'),
        ),
    ]
