# Generated by Django 4.0.5 on 2022-07-26 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_tag_user_id_video_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_share',
            fields=[
                ('Video_share_count', models.AutoField(default='0', primary_key=True, serialize=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
                ('Video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.video')),
            ],
        ),
        migrations.CreateModel(
            name='Video_Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_reaction', models.CharField(choices=[('1', 'Like'), ('2', 'Love'), ('3', 'Dislike'), ('4', 'Sad'), ('5', 'Congratulations')], max_length=100)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
                ('Video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.video')),
            ],
        ),
        migrations.CreateModel(
            name='Video_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.tag')),
                ('Video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.video')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user_id')),
                ('Video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.video')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Comments_ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Comments', models.CharField(max_length=500)),
                ('Date_Time', models.DateTimeField(auto_now_add=True)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user_id')),
            ],
        ),
    ]
