# Generated by Django 4.1 on 2022-08-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_video_share_video_reaction_video_category_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Date_Time',
            field=models.DateTimeField(),
        ),
    ]
