# Generated by Django 4.0.5 on 2022-08-10 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_login_remove_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='video_reaction',
            name='User',
        ),
        migrations.RemoveField(
            model_name='video_share',
            name='User',
        ),
        migrations.AddField(
            model_name='video_reaction',
            name='User_Main',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='userapp.user_main'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_share',
            name='User_Main',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='userapp.user_main'),
            preserve_default=False,
        ),
    ]
