# Generated by Django 4.0.5 on 2022-08-10 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_user_main_remove_video_reaction_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_Email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_ID_Front_View', models.ImageField(upload_to='idcards_frontview')),
                ('School_ID_Back_View', models.ImageField(upload_to='idcards_backview')),
                ('User_Main', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapp.user_main')),
            ],
        ),
    ]
