# Generated by Django 4.0.5 on 2022-08-11 08:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_validation2_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Video_description', models.CharField(max_length=300)),
                ('Video_File', models.FileField(upload_to='video/%y', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['Mp4'])])),
                ('Date_Time', models.DateTimeField(auto_now_add=True)),
                ('Video_Visibility', models.CharField(choices=[('1', 'Private'), ('2', 'Public')], max_length=100)),
            ],
            options={
                'ordering': ['-Date_Time'],
            },
        ),
        migrations.RemoveField(
            model_name='history',
            name='Video',
        ),
        migrations.RemoveField(
            model_name='video_category',
            name='Video',
        ),
        migrations.RemoveField(
            model_name='video_reaction',
            name='Video',
        ),
        migrations.RemoveField(
            model_name='video_share',
            name='Video',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='history',
            name='Video_Files',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='userapp.video_files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_category',
            name='Video_Files',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='userapp.video_files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_reaction',
            name='Video_Files',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='userapp.video_files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_share',
            name='Video_Files',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='userapp.video_files'),
            preserve_default=False,
        ),
    ]
