# Generated by Django 4.1 on 2022-08-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_video_date_time'),
        ('userapp', '0008_video_files_remove_history_video_and_more'),
    ]

    operations = [
    ]
